const commands = [
    {command: "/kill yman234\n", name: "Kill Me"},
    {command: "/give @p netherite_sword{Enchantments:[{id:sharpness,lvl:1000}]}\n", name: "Supa Sword"},
    {command: "/fill 2 63 1 2 63 1 minecraft:redstone_block\n", name: "Ride Snowball", repeat: true},
    {command: "/fill 4 63 1 4 63 1 minecraft:redstone_block\n", name: "Human Drill", repeat: true},
    {command: "/execute at yman234 run summon tnt ~ ~ ~\n", name: "Tnt"},
    {command: "/fill 3 63 1 3 63 1 minecraft:redstone_block\n", name: "Auto Bridge", repeat: true},
    {command: "/clear yman234\n", name: "Clear Items"},
    {command: "/kill  @e[type=!player,type=!ocelot,type=!wolf,type=!armor_stand]\n", name: "Kill Mobs"},
    {command: "/execute at yman234 run summon minecraft:wither ^ ^2 ^2\n", name: "Spawn Wither"},
    {command: "/execute at yman234 run summon minecraft:ender_dragon ^ ^2 ^2\n", name: "Spawn Ender Dragon"},
    {command: "/execute at yman234 run summon minecraft:elder_guardian ^ ^2 ^2\n", name: "Spawn Elder Guardian"},
    {command: "zombie", name: "Zombie Hoard", hoard: true},
    {command: "blaze", name: "Blaze Hoard", hoard: true},
    {command: "cow", name: "THE COW BRIGADE", hoard: true},
    {command: "", name: "Full Armor", special: true},
    {command: "/kill @e\n", name: "Kill Everything"},
    {command: "/give yman234 minecraft:ender_eye 64\n", name: "Spawn Eyes of Ender"},
    {command: "/execute in the_end run tp yman234 -80 58 -47\n", name: "Go to the End"},
    {command: "/execute in the_nether run tp yman234 -80 58 -47\n", name: "Go to the Nether"},
    {command: "/execute in minecraft:overworld run tp yman234 -128 66 -91\n", name: "Go to the Overworld"},
    {command: `/give @p minecraft:bow{Enchantments:[{id:"minecraft:sharpness",lvl:999999999},{id:"minecraft:power",lvl:999999999},{id:"minecraft:flame",lvl:999999999},{id:"minecraft:infinity",lvl:1}]}\n`, name: "Bumpin Bow", special: true},
    {command: '/fill 5 63 1 5 63 1 minecraft:redstone_block\n', name: "Snowball Art", repeat: true},
];
module.exports = commands;