const commands = [
    {command: "/kill  @e[type=!player,type=!ocelot,type=!wolf,type=!armor_stand]\n", name: "Kill Mobs"},
    {command: "/kill  @e[type=!player,type=!ocelot,type=!wolf,type=!armor_stand]\n", name: "Kill Mobs"},
    {command: "/execute at yman234 run summon minecraft:elder_guardian ^ ^2 ^2\n", name: "Spawn Elder Guardian"},
    {command: "/execute at yman234 run summon minecraft:vindicator ^ ^2 ^2\n", name: "Lone Vindicator"},
    {command: "/fill 2 63 1 2 63 1 minecraft:redstone_block\n", name: "Ride Snowball", repeat: true},
    {command: "husk", name: "Husk Hoard", hoard: true},
    {command: "blaze", name: "Blaze Hoard", hoard: true},
    {command: "turtle", name: "Turtle Squad", hoard: true},
    {command: "cod", name: "Fish Fumble", hoard: true},
    {command: "skeleton", name: "Gaggle Of Skeletons", hoard: true},
    {command: `/give @p minecraft:bow{Enchantments:[{id:"minecraft:power",lvl:1}]}\n`, name: "Ok Bow", special: true},
    {command: "/give @p iron_sword{Enchantments:[{id:sharpness,lvl:1}]}\n", name: "Mid Sword"},
    {command: "/give @p iron_pickaxe{Enchantments:[{id:efficiency,lvl:2}]}\n", name: "Iron Pickaxe"},
    //less rares
    {command: '/fill 5 63 1 5 63 1 minecraft:redstone_block\n', name: "Snowball Art", repeat: true},
    {command: "/clear yman234\n", name: "Clear Items"},
    {command: "/fill 3 63 1 3 63 1 minecraft:redstone_block\n", name: "Auto Bridge", repeat: true},
    {command: "/execute at yman234 run summon tnt ~ ~ ~\n", name: "Tnt"},
    {command: "warden", name: "THE WARDENS", hoard: true},
    {command: "", name: "IRONE Armor", special: true},//new
    {command: `/give @p minecraft:bow{Enchantments:[{id:"minecraft:power",lvl:1}]}\n`, name: "Pokey Bow", special: true},
    {command: "/effect give yman234 minecraft:poison 60\n", name: "Poison.."},
    {command: "/fill 6 63 1 6 63 1 minecraft:redstone_block\n", name: "Tnt Chase", special: true},//new
    {command: "/give @p iron_sword{Enchantments:[{id:sharpness,lvl:3}]}\n", name: "Avg Sword"},
    {command: "/give @p golden_pickaxe{Enchantments:[{id:efficiency,lvl:1000}]}\n", name: "Gol D. Pick"},
    {command: "/give @p elytra\n", name: "Elytra"},
    {command: "/tp yman234 -1000 122 1000\n", name: "Back to Spawn"},
    //rares consider beacon
    {command: "/execute at yman234 run summon minecraft:ender_dragon ^ ^2 ^2\n", name: "Spawn Ender Dragon"},
    {command: "", name: "Full Armor", special: true},
    {command: `/give @p minecraft:bow{Enchantments:[{id:"minecraft:power",lvl:999999999},{id:"minecraft:flame",lvl:999999999},{id:"minecraft:infinity",lvl:1}]}\n`, name: "Bumpin Bow", special: true},
    {command: '/execute at yman234 run clone -12 58 2 -8 63 6 ~-2 ~-4 ~-2\n', name: "Checkpoint"},
    {command: "/kill yman234\n", name: "Kill Me"},
    {command: "/fill 4 63 1 4 63 1 minecraft:redstone_block\n", name: "Human Drill", repeat: true},
    {command: "/kill @e\n", name: "Kill Everything"},
    {command: "/execute at yman234 run summon minecraft:wither ^ ^2 ^2\n", name: "Spawn Wither"},
    {command: "/give @p netherite_pickaxe{Enchantments:[{id:efficiency,lvl:1000}]}\n", name: "PICK-axe ME"},
    {command: `/execute at yman234 run summon minecraft:villager ^ ^2 ^2 {CustomName:'{"text":"BigBaldSK"}'}\n`, name: "BigBaldSK"},
    {command: "/give @p netherite_sword{Enchantments:[{id:sharpness,lvl:1000}]}\n", name: "Supa Sword"},
];
module.exports = commands;